name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - ipywidgets=7.6.3 
  - pandas-profiling=3.1.0
  - pyarrow=2.0
  - numba>=0.53.1
  - matplotlib=3.4.2
  - pip:
      - wandb==0.16.0
      - pydantic<=1.8.2  # Ensure compatibility with pandas-profiling